### ISSUE TITLE
headerbar-/titlebar title color

### ISSUE THREAD

**Issue by blue-devil-93** [thesquash/gtk-theme-raleigh#1]
Please consider something like this:

headerbar .title, headerbar label.title,
.titlebar .title, .titlebar label.title {
color: white;
}
And there we have the same thing that i had to think about with the mate traditional themes. Headerbar did not exist time these themes where created  so you have to find a solution on your own.

**Comment by thesquash** [comment]
https://github.com/thesquash/gtk-theme-raleigh/commit/a77dc29449ff9a45e348c45e3901f8c6eac3b6bd

Thanks for the tip!
