### ISSUE TITLE
Transparent bar in Tilix

### ISSUE THREAD

**Issue by emirror-de** [thesquash/gtk-theme-raleigh#4]
Hi there,
thanks for reviving this awesome theme!
I do have one question. In Tilix the bar below the titlebar is transparent. Is this intentionally?

![screenshot-2022-05-13_18-05-1652458971](https://user-images.githubusercontent.com/30552361/168326470-5c9b2b69-41c9-486e-8253-195f6180041f.jpg)

Best regards,
Lewin

**Comment by thesquash** [comment]
No, it's not intentional.  I have no idea what triggers this.  I'm going to have to install Tilix myself (sigh) and see what's going on here.

**Comment by emirror-de** [comment]
I found out that this has something to do with the background color. I also use `waybar` and tried to use the `theme_bg_color` variable and also got a transparent bar after reloading. The waybar wiki refers to [Adwaita color variables](https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/theme/Adwaita/_colors-public.scss) where I found the variable.

When I add it to the `main.css` the correct background color is shown. I opened up a draft PR #5  so that you can have a look if what I did is in your sense and if I am missing something.

**Comment by thesquash** [comment]
Thanks for the contribution!
