### ISSUE TITLE
Thunar rubberband selection obscures selected items

### ISSUE THREAD

**Issue by commandlinegamer** [thesquash/gtk-theme-raleigh#9]
I've noticed when using rubberband selection of icons (list or icon view) in Thunar, the selected region is the same colour as the window background (i.e. white or dark grey depending on which version of the theme is active) and therefore covers up the icons under selection.

So, I've added the following to the Raleigh/gtk-3.0/application-styles/thunar.css file:

```
window.thunar widget.view.rubberband
{
        background-color: alpha (@selected_bg_color, 0.3);
        border-color: @fg_color;
        border-style: solid;
        border-width: 1px;
        border-radius: 2px;
}
```

Hope this is of some help.

I really appreciate this release, as I am just not a fan of flat themes.

**Comment by thesquash** [comment]
Thank you!  I just committed (most of) your changes to this repository.

There was one thing that I took issue with though.  The border radius seemed too non-classic.  Sorry, but part of the the motivation behind this theme is to create a theme that mimics the original Raleigh as closely as possible, and Raleigh was not known for its rounded corners.  Everything else is great (thank you), and I even changed the Caja rubberbanding style to match this one for Thunar.

Thanks yet again!
